fail_fast: false
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      #- id: terraform_tflint
      #- id: terraform_tfsec
      #- id: checkov
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-executables-have-shebangs
  - repo: git://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shfmt
        args: ['-l', '-i', '2', '-ci', '-sr', '-w']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.11.1
    hooks:
      - id: yamllint
        files: \.(yaml)$
